server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/app/data/knowledge_base.db
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: ${java.io.tmpdir}

file:
  upload-dir: /app/data/uploads

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
